version: "3.8"

services:
  app:
    build: .
    container_name: tarefas
    ports:
     - "8000:8000"
    volumes:
     - .:/app
    environment:
     - .env
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]